### ISSUE TITLE
Elm Editor fails with 400 error, "request too large"

### ISSUE THREAD

**Issue by Erudition** [elm-fullstack/elm-fullstack#15]
Error:
BadStatus: 400
Response body: Request is too large.

To reproduce: go to
https://elm-editor.com/?project-state=https%3A%2F%2Fgithub.com%2FErudition%2FMinder%2Ftree%2Fc4d7b9b5304c576e22e997bb1e34744331485d2f%2Felm&project-state-hash=9beae94286364065b977c9178e2ecee3063733b73aed17697923c0ff297bb908

**Comment by Viir** [comment]
This happens because the demo instance at elm-editor.com is configured for an HTTP request size limit of one megabyte. You can see the configuration entry here:
https://github.com/elm-fullstack/elm-fullstack/blob/446309269eea4bc367730fa8f976f756ab0ac8f0/implement/example-apps/elm-editor/elm-fullstack.json#L6

You can avoid this error by increasing this number on your deployment of Elm Editor.

Seeing this error, I think we can improve the specificity of the HTTP status code. 413 seems a good candidate.

**Comment by Erudition** [comment]
Ah interesting. Well, I don't have a personal deployment of elm-editor. I wanted to see it work on the demo instance, I feel like 1 megabyte is too small. Oh well

**Comment by Viir** [comment]
No problem, I adapted the public demo instance to remove the limit of one megabyte and support this scenario too.

**Comment by Erudition** [comment]
Awesomeeee!

Now the issue is that every file fails to load with:
```
Errors
NO elm.json FILE
It looks like you are starting a new Elm project. Very exciting! Try running:

    elm init

It will help you get set up. It is really simple!
```

...which seems correct because the elm.json file (which does exist in the imported git repo) does not show up in the files in the sidebar.

Happy to turn this into a separate issue if you'd like!

**Comment by Viir** [comment]
> Awesomeeee!
> 
> Now the issue is that every file fails to load with:
> 
> ```
> Errors
> NO elm.json FILE
> It looks like you are starting a new Elm project. Very exciting! Try running:
> 
>     elm init
> 
> It will help you get set up. It is really simple!
> ```
> 
> ...which seems correct because the elm.json file (which does exist in the imported git repo) does not show up in the files in the sidebar.
> 
> Happy to turn this into a separate issue if you'd like!

Yes, that does not look related to the current title above, so it would be better to place this in a separate thread. Thank you for improving the navigation for future users.

**Comment by Viir** [comment]
For future visitors, here is a commit with a change to increase the supported workspace sizes:

https://github.com/elm-fullstack/elm-fullstack/commit/20ee2fc08eb94d413da675dfda0138b3858ac624

You can use a change like this on your deployment to support larger projects.
