### ISSUE TITLE
elm-fs cannot install

### ISSUE THREAD

**Issue by guibbv2011** [elm-fullstack/elm-fullstack#5]
Hi dear,

I'm trying to install elm-fs for running a project example,
but without success.. 

my machine is: Ubuntu 20.10, 64-bit

thanks in advance

**Comment by Viir** [comment]
Thank you for letting us know.

Currently, the only function of the install command is to register the `elm-fs` command so that we can use it from any terminal. So an immediate workaround is to do this registration manually.
For manual registration, I would try the approach from https://askubuntu.com/questions/118312/how-can-i-create-a-custom-terminal-command-to-run-a-script/118320#118320

I will look into fixing the install command for Ubuntu 20.

**Comment by Viir** [comment]
I was able to reproduce the problem on Ubuntu 20. The process is documented at https://github.com/elm-fullstack/elm-fullstack/commit/c2f034b216e3a73bb8f5fcb9820bd5237055e40c

**Comment by Viir** [comment]
Release 2021-06-16 fixes this issue. The installation on Linux now uses the approach implemented with https://github.com/elm-fullstack/elm-fullstack/commit/0774c4fc344b0cf3f2ea5b5e9ab8aee5f8d86d46

Following are the commands for installing on Ubuntu 20.10:

```PS
docker run  -p 5000:5000 -p 4000:4000  --name=ubuntu  -t -i ubuntu:20.10  bash

apt-get update && apt-get install -y wget && apt-get install -y unzip

wget  https://github.com/elm-fullstack/elm-fullstack/releases/download/v2021-06-16/elm-fullstack-bin-0774c4fc344b0cf3f2ea5b5e9ab8aee5f8d86d46-linux-x64.zip

unzip  elm-fullstack-bin-0774c4fc344b0cf3f2ea5b5e9ab8aee5f8d86d46-linux-x64.zip

chmod a+x  elm-fs

./elm-fs  install
```

The docker run command above also exposes ports for further testing and administration from outside. Skip the docker to work directly on the host system.

Now the system is ready to run productive commands like this one:

```text
elm-fs  run-server  --admin-password=test  --public-urls="http://*:5000"  --deploy-app-from=https://github.com/elm-fullstack/elm-fullstack/tree/6d96fca86dc807208e923caffb94a449d6f4b22d/implement/example-apps/docker-image-default-app
```

**Comment by guibbv2011** [comment]
Hi, @Viir 

Yeah this works fine, 
I liked your project rich-chat-room

Thanks
